@startuml
title POST /api/productos

actor Cliente
Cliente -> ProductController : POST /api/productos (body=ProductoDTO)
ProductController -> ProductService : createOrUpdateProduct(producto)
ProductService -> IProductRepository : save(producto)
IProductRepository --> ProductService : void
ProductService --> ProductController : ProductoDTO
ProductController --> Cliente : 200 OK + ProductoDTO
@enduml
